import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ReduxProvider from '@/redux/Provider';
import './globals.scss';

const inter = Inter({
  subsets: ['latin'],
  weigth: ['300', '600'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Taxi App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
